# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='show_title',
            field=models.BooleanField(default=True),
        ),
    ]
