# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_page_show_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='footer_column_count',
            field=models.IntegerField(default=4),
        ),
    ]
