# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20170125_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, upload_to='./static/uploads'),
        ),
    ]
